# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
color_theme              : #5e9498
# Site Settings
locale                   : "en-US"
title                    : "Learning Deep"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "박재현"
description              : #":blush:"
url                      : # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "Cabbalett/Cabbalett"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : #"/assets/bio-image.jpg"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : false # true, false (default)
words_per_minute         : 50
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "giscus", "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : "github-light" # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
  giscus:
    repo_id              : # Shown during giscus setup at https://giscus.app
    category_name        : # Full text name of the category
    category_id          : # Shown during giscus setup at https://giscus.app
    discussion_term      : # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : # '1' for enabled (default), '0' for disabled
    theme                : # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
  staticman:
    branch               : # "master"
    endpoint             : # "https://{your Staticman v3 API}/v3/entry/github/"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : # true, false (default)
search                   : # true, false (default)
search_full_content      : # true, false (default)
search_provider          : # lunr (default), algolia, google
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-1P3TT0YMNM"
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "박재현"
  avatar           : "/assets/bio-image1.jpg"
  bio              : "KAIST 18 :file_folder:"
  location         : "Yuseong, Daejeon"
  email            : "jhpark00813@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://www.github.com/Cabbalett"
    - label: "CV"
      icon: "fas fa-paste"
      url: "https://drive.google.com/file/d/1WEekw65Na1G8_SAFR2B10Oap_keRYC7q/view?usp=sharing"
  #  - label: "Email"
  #    icon: "fas fa-fw fa-envelope-square"
  #    url: "jhpark00813@gmail.com"
    - label: "Bio"
      icon: "fas fa-fw fa-link"
      url: /bio
  #  - label: "Twitter"
  #    icon: "fab fa-fw fa-twitter-square"
  #    url: "https://twitter.com/"
  #  - label: "Facebook"
  #    icon: "fab fa-fw fa-facebook-square"
  #    url: "https://facebook.com/"
    
  #  - label: "Instagram"
  #    icon: "fab fa-fw fa-instagram"
  #    url: "https://www.instagram.com/p_reenact/"


# Site Footer
#footer:
  #links:
  #  - label: "Twitter"
  #    icon: "fab fa-fw fa-twitter-square"
  #    # url:
  #  - label: "Facebook"
  #    icon: "fab fa-fw fa-facebook-square"
  #    # url:
  #  - label: "GitHub"
  #    icon: "fab fa-fw fa-github"
  #    # url:
  #  - label: "GitLab"
  #    icon: "fab fa-fw fa-gitlab"
  #    # url:
  #  - label: "Bitbucket"
  #    icon: "fab fa-fw fa-bitbucket"
  #    # url:
  #  - label: "Instagram"
  #    icon: "fab fa-fw fa-instagram"
  #    # url:


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
      sidebar:
        nav: "docs"

# Site
# repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Jaehyun Park
job_title: Master Student @ Data Mining Lab, KAIST
email: jhpark813@kaist.ac.kr
# email_title: Email (Email title override)
# phone_title: Phone (Phone title override)
website: https://cabbalett.github.io/
website_title: Blog

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username:  Cabbalett
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
additional_links:
- title: CV
  icon: fas fa-paste
  url: https://drive.google.com/file/d/1WEekw65Na1G8_SAFR2B10Oap_keRYC7q/view?usp=sharing
# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "G-SYCG1ELX3E"
# google_analytics: "G-SYCG1ELX3E"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a master's student in Data Mining Lab, KAIST. My research interests are active learning, data selection/curation, and efficient ML.

  I like to understand the task deeply and try to lead a group to make reasonable results.
content:

  - title: Experience
    layout: list
    content:
      - layout: left
        border: weak
        title: IBS Data Science Group
        sub_title: Research Intern
        caption: July 2022 - Present
        description: | # this will include new lines to allow paragraphs
          Research on **Technical Progress in Social Activities**. Utilizing meetup.com dataset for longitudinal studies tracing the changes in contents and descriptions of a specific type of social activities driven by technological environment.

          Learned about:
            - Natural Language Processing: Word2Vec, Topic Modeling, Gensim, nltk
            - Exploratory Data Analysis

          <a href="https://drive.google.com/file/d/1ABPHR07JeSjnyME7bs80YiBEN8zv9kYW/view?usp=share_link">Paper</a>
          
      - layout: left
        border: weak
        title: Boostcamp AI Tech
        sub_title: Student
        caption: AUG 2021 - DEC 2021
        description: | # this will include new lines to allow paragraphs
          I got a chance to study in a coding camp to experience End-to-End AI production process. I was able to learn to define tasks and implement various neural network architectures via <mark>PyTorch</mark>.
          I participated in image classification, semantic segmentation, object detection, model optimization competitions and develop my knowledge.

          Learned about:
          - Computer Vision: Image Classification, Object Detection, Semantic Segmentation
          - Basic NLP: RNN, LSTM/GRU, Transformer
          - Model Optimization: Model Pruning, AutoML(Optuna), Model Quantization
          - Data Visualization: Exploratory Data Analysis, Seaborn
          - Product Serving: FastAPI, Docker, GCP

      - layout: left
        title: SK Hynix Information Sensor Technology
        sub_title: Intern
        caption: JUN 2021 - AUG 2021
        description: | # this will include new lines to allow paragraphs
          Participated in investigation of depth-sensing error dependency on demodulation constrast.

  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: KAIST(Korea Advanced Institute of Science & Technology)
        sub_title: Computer Science
        caption: MAR 2023 - Present, Master
      - layout: top-middle
        title: KAIST(Korea Advanced Institute of Science & Technology)
        sub_title: Electrical Engineering / Computer Science
        caption: MAR 2018 - FEB 2023, Bachelor

  - title: Publications
    layout: list
    content:
      - layout: top
        title: Exploiting Representation Curvature for Boundary Detection in Time Series
        sub_title: NeurIPS 2024
        caption: Y. Shin, <b>J. Park</b>, S. Yoon, B. Lee, JG. Lee<sup>*</sup>
        additional_links:
          - title: pdf
            icon: "far fa-file-pdf"
            url: https://openreview.net/pdf?id=WK2KxPAMQv
        
  - title: Awards
    layout: list
    content:
      - layout: top-middle
        title: Dean's List
        sub_title: KAIST
        caption: 2022 Spring
        description: |
          Individuals with outstanding academic performance, good conduct and exemplary behavior who have been recommended by the Head of the Department.

          Within top 3% of academic performance.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Image Captioning
        link: https://cabbalett.github.io/Image-Captioning/
        # link_text: Blog link
        additional_links:
          - title:  github link
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        sub_title: >
          Personal Project
        description: | # this will include new lines to allow paragraphs
          Implementation of Show-and-Tell model from scratch. Based from simple RNN and CNN background knowledge, I wanted to take a step further and learn
          linking the two architecture to develop a model with an interesting task.
      - layout: top
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Channel-wise Pruning
        link: https://cabbalett.github.io/week17/Week17-1/
        # link_text: Blog link
        additional_links:
          - title:  github link
            icon: fab fa-github
            url: https://github.com/Cabbalett/Pruning
        sub_title: >
          Personal Project
        description: | # this will include new lines to allow paragraphs
          A Project about pruning a VGGNet by structured pruning method.
      - layout: top
        border: weak
        title: Personal Mobility Violation Detection
        # link_text: Blog link
        additional_links:
          - title:  github link
            icon: fab fa-github
            url: https://github.com/Cabbalett/final-project-level3-cv-01
        sub_title: >
          Team Project@Boostcamp
        description: | # this will include new lines to allow paragraphs
          Developing a YOLO based model to detect kickboard user violation, such as no helmet, more than one rider. I was in charge of the YOLO modeling and Exploratory Data Analysis.
      - layout: top
        title: Today I Learned
        link: https://cabbalett.github.io/
        # link_text: Blog link
        sub_title: >
          Personal Blog
        description: | # this will include new lines to allow paragraphs
          I try to organize what I've learnt using the Blog. You can check what I have been learning.
          
  - title: Courses
    layout: list
    content:
      - layout: top
        title: Probability and Introductory Random Processes
        sub_title: Electrical Engineering
        caption: A+
        description: | # this will include new lines to allow paragraphs
          Learned about basics of probability, MLE/MAP estimation, basics of Machine Learning and speech recognition
      - layout: top
        title: Database and Big Data Systems
        sub_title: Electrical Engineering
        caption: A+
        description: | # this will include new lines to allow paragraphs
          Learned about ER Model, Design Theory, <mark>MySQL</mark>
      - layout: top
        title: Foundation of Big Data Analytics
        sub_title: Electrical Engineering
        caption: A+
        description: |
          Learned about <mark>Spark</mark>, clustering, dimensionality reduction, recommendation systems, link analysis, data streams, large-scale machine learning, web advertising.
      - layout: top
        title: AI Convergence Capstone Design
        sub_title: Special Topics in Electrical Engineering
        caption: A+
        description: | # this will include new lines to allow paragraphs
          Learned about Self-supervised Learning Tasks, anomaly detection, t-SNE plot. Participated in an internal competition, and got 1st place. I was the moderator of out team activity and organized the experiment schedules and researches.

          <a href="https://dcase.community/challenge2020/task-unsupervised-detection-of-anomalous-sounds-results">Detecting Anomalous Sounds for Machine Condition Monitoring</a>

          Activity of our group project is organized <a href="https://cabbalett.notion.site/EE488-Team-Project-1d2e82952e144465acc7c573d7003477">here</a>.
      - layout: top
        title: Machine Learning
        sub_title: Computer Science
        caption: A+
        additional_links:
          - title:  github link
            icon: fab fa-github
            url: https://github.com/Cabbalett/CS376_ImageCaptioningPruning
        description: | # this will include new lines to allow paragraphs
          Learned about
          - Basic Neural Net Models: MLP, CNN, RNN, LSTM, Attention Module
          - Classic ML Techniques: SVM, Decision Tree, Random Forest, Ensemble, PCA

          Our group project was about Pruning an Image Captioning Model. I was responsible as the leader of the team, and combined my previous projects to make a new topic to do research on.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I like to go swimming in my free time.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

# plugins:
#  - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
